### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by zipme** [kentcdodds/full-stack-components#5]
hi @kentcdodds  Thanks for the full stack component tutorial. Just one question, how do you do error handling for when the [resource loader](https://github.com/kentcdodds/full-stack-components/blob/main/apps/02-after/app/routes/resources/customers.tsx#L13) errors out? 

Since this is not a route component we can't use the error boundary here right? Or is the error got propagated to the route level?

**Comment by kentcdodds** [comment]
Hi @zipme,

Yeah, for these you want to return data with an error message which you can display in the component.
